---
title: 输出是什么？
pubDatetime: 2021-07-03T22:11:18.000Z
author: caorushizi
tags:
  - 选择题
postSlug: 7288dc5d-1485-4275-8a19-acf2bdc7f909
description: >-
  (() => { let x, y try { throw new Error() } catch (x) { (x = 1), (y = 2)
  console.log(x) } console.log(x) console.log(y) })() catch 代码块接收参数
  x。当我们传递参数时，这与之前定义的变量 x 不同 。这个 x 是属于 catch 块级作用域的。 然后，我们将块级作用域
difficulty: 0.5
questionNumber: 44
source: https://fe.ecool.fun/topic/7288dc5d-1485-4275-8a19-acf2bdc7f909
---

```javascript
(() => {
  let x, y;
  try {
    throw new Error();
  } catch (x) {
    (x = 1), (y = 2);
    console.log(x);
  }
  console.log(x);
  console.log(y);
})();
```

---

`catch` 代码块接收参数 `x`。当我们传递参数时，这与之前定义的变量 `x` 不同 。这个 `x` 是属于 `catch` 块级作用域的。
然后，我们将块级作用域中的变量赋值为 `1`，同时也设置了变量 `y` 的值。现在，我们打印块级作用域中的变量 `x`，值为 `1`。
`catch` 块之外的变量 `x` 的值仍为 `undefined`， `y` 的值为 `2`。当我们在 `catch` 块之外执行 `console.log(x)` 时，返回 `undefined`，`y` 返回 `2`。
