{
  "data": {
    "id": 499,
    "exerciseKey": "aaee81ad-a128-4bbf-b60b-aa2c9c3396c3",
    "category": "QA",
    "renderType": "md",
    "title": " Promise中，resolve后面的语句是否还会执行？",
    "desc": null,
    "options": null,
    "explanation": "在 JavaScript 中，当调用 `Promise.resolve(value)` 后，Promise 会立即变成已解决状态（fulfilled），`value` 会作为结果传递。但`resolve` 后面的语句会继续执行，因为 `resolve` 只是将 Promise 的状态更改为已解决，它不会中断或停止代码的执行。\n\n以下是一个例子：\n\n```javascript\nnew Promise((resolve, reject) => {\n  console.log(\"Promise started\");\n  resolve(\"Resolved value\");\n  console.log(\"After resolve\");\n}).then(value => {\n  console.log(value);\n});\n```\n\n输出是：\n\n```\nPromise started\nAfter resolve\nResolved value\n```\n\n这表明 `resolve` 后面的 `console.log(\"After resolve\")` 语句确实会被执行。",
    "pivot": "",
    "vipLimit": 0,
    "level": 3,
    "appId": 7,
    "createAt": "2021-07-11T07:25:21.000Z",
    "updateAt": "2024-08-10T17:05:25.000Z",
    "isCollected": false,
    "currentIndex": 1001,
    "filterTotalNum": 1487,
    "prev": "fbcd6444-9c0f-492a-b138-bd205bb4bf1d",
    "next": "8e0a5da4-74f1-4dcd-9217-bc151cd93870"
  },
  "post": {
    "exerciseKey": "aaee81ad-a128-4bbf-b60b-aa2c9c3396c3",
    "category": "QA",
    "title": " Promise中，resolve后面的语句是否还会执行？",
    "level": 3,
    "createAt": "2021-07-11T07:25:21+00:00",
    "updateAt": "2024-08-10T17:05:25+00:00"
  },
  "tag": {
    "id": 10,
    "tagName": "JavaScript",
    "type": "1",
    "exerciseCount": 379
  }
}